-- Core tables — foundational schema (resolves INVESTIGATION.md RISK-3).
--
-- These tables previously existed only as Drizzle TypeScript definitions with
-- no SQL migration. This file is hand-written to match the Drizzle schema
-- exactly:
--   users / sessions / login_attempts  -> lib/db/src/index.ts
--   settings / settings_audit          -> lib/db/src/schema/settings.ts
--   submissions                        -> lib/db/src/schema/submissions.ts
--   link_generations                   -> lib/db/src/schema/links.ts
--
-- Numbered 0000 so it runs before 0001/0002/0003. `marketing_sources` is NOT
-- here — it already has its own migration (0002_marketing_sources.sql).
--
-- Idempotent (IF NOT EXISTS throughout). Apply manually:
--   psql "$DATABASE_URL" -f 0000_core_tables.sql

BEGIN;

-- ---- users ----------------------------------------------------------------
-- Admin accounts. No public signup — populated by the seed script.
CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    name text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz
);

-- ---- sessions -------------------------------------------------------------
-- Opaque server-side session ids. Cookie holds the id only.
CREATE TABLE IF NOT EXISTS sessions (
    id text PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_expires_at_idx ON sessions (expires_at);

-- ---- login_attempts -------------------------------------------------------
-- Per-email rate-limiting ledger.
CREATE TABLE IF NOT EXISTS login_attempts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email text NOT NULL,
    ip_address text,
    succeeded boolean NOT NULL,
    attempted_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS login_attempts_email_attempted_at_idx
    ON login_attempts (email, attempted_at);

-- ---- settings -------------------------------------------------------------
-- Key/value admin toggles.
CREATE TABLE IF NOT EXISTS settings (
    key text PRIMARY KEY,
    value jsonb NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text NOT NULL
);

CREATE TABLE IF NOT EXISTS settings_audit (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    key text NOT NULL,
    old_value jsonb,
    new_value jsonb NOT NULL,
    actor_email text NOT NULL,
    note text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS settings_audit_key_idx
    ON settings_audit (key, created_at);

-- ---- submissions ----------------------------------------------------------
-- Intake submissions from both DrSnip forms. Created here in its final
-- post-Phase-2 shape; 0003_drsnip_schema.sql then no-ops against it (all of
-- its ALTERs are IF EXISTS / IF NOT EXISTS).
CREATE TABLE IF NOT EXISTS submissions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    form_type text NOT NULL DEFAULT 'registration',
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    date_of_birth text,
    state_residence text,
    insurance_card_front_filename text,
    insurance_card_back_filename text,
    has_insurance_cards boolean NOT NULL DEFAULT false,
    raw_payload jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS submissions_created_at_idx ON submissions (created_at);
CREATE INDEX IF NOT EXISTS submissions_email_idx ON submissions (email);
CREATE INDEX IF NOT EXISTS submissions_form_type_idx ON submissions (form_type);

-- ---- link_generations -----------------------------------------------------
-- History of campaign URLs generated by the internal link tool.
CREATE TABLE IF NOT EXISTS link_generations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text NOT NULL,
    source text NOT NULL,
    campaign text,
    event text,
    utm_source text,
    utm_medium text,
    utm_campaign text,
    generated_url text NOT NULL
);

CREATE INDEX IF NOT EXISTS link_generations_created_at_idx
    ON link_generations (created_at);
CREATE INDEX IF NOT EXISTS link_generations_created_by_idx
    ON link_generations (created_by, created_at);

COMMIT;
